# Generated by Django 3.0.7 on 2022-01-14 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('estado_notificacion', models.BooleanField(default=True)),
                ('prox_cita', models.DateField(auto_now=True)),
                ('tipo', models.CharField(choices=[('V-', 'V-'), ('J-', 'J-'), ('E-', 'E-')], default='V-', max_length=10)),
                ('cedula', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Número de Cédula')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=40, verbose_name='Apellidos')),
                ('direccion', models.TextField(verbose_name='Direccion Habitacional')),
                ('co_movil', models.CharField(blank=True, choices=[('0412', '0412'), ('0416', '0416'), ('0426', '0426'), ('0414', '0414'), ('0424', '0424')], max_length=20, null=True)),
                ('movil', models.CharField(blank=True, max_length=11, null=True, verbose_name='Número de Celular')),
                ('tlf', models.CharField(blank=True, max_length=11, null=True, verbose_name='Número de Telefonico')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico')),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupación Laboral')),
                ('updated', models.DateField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('estado_notificacion', models.BooleanField(default=True)),
                ('prox_cita', models.DateField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fnaci', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexom', models.CharField(max_length=40, verbose_name='sexo')),
                ('razam', models.CharField(max_length=50, verbose_name='raza')),
                ('peso', models.IntegerField(verbose_name='Peso')),
                ('especie', models.CharField(max_length=50, verbose_name='especie')),
                ('updated', models.DateField(auto_now=True, verbose_name='Fecha de edición')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regmedic.Cliente')),
            ],
            options={
                'verbose_name_plural': 'Mascotas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('estado_notificacion', models.BooleanField(default=True)),
                ('prox_cita', models.DateField(auto_now=True)),
                ('nomva', models.TextField(verbose_name='Nombre de la Vacuna/s')),
                ('fechav', models.DateField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('dosis', models.TextField(verbose_name='Dosis')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regmedic.Mascota')),
            ],
            options={
                'verbose_name_plural': 'Vacunaciones',
                'ordering': ['fechav'],
            },
        ),
        migrations.CreateModel(
            name='Despa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('estado_notificacion', models.BooleanField(default=True)),
                ('prox_cita', models.DateField(auto_now=True)),
                ('despa', models.TextField(blank=True, null=True, verbose_name='Desparasitante')),
                ('descripcion', models.TextField(blank=True, default='', null=True, verbose_name='Descripcion')),
                ('fechad', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regmedic.Mascota')),
            ],
            options={
                'verbose_name_plural': 'Desparasitaciones',
                'ordering': ['fechad'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('estado_notificacion', models.BooleanField(default=True)),
                ('prox_cita', models.DateField(auto_now=True)),
                ('motivo', models.TextField(verbose_name='Motivo de Consulta')),
                ('sintomas', models.TextField(blank=True, null=True, verbose_name='Sintomas Presentados')),
                ('diapre', models.TextField(blank=True, null=True, verbose_name='Diagnostico Presuntivo')),
                ('diadef', models.TextField(blank=True, null=True, verbose_name='Diagnostico Definitivo')),
                ('temp', models.TextField(blank=True, null=True, verbose_name='Temperatura')),
                ('frecar', models.TextField(blank=True, null=True, verbose_name='Frecuencia Cardiaca')),
                ('freres', models.TextField(blank=True, null=True, verbose_name='Frecuencia Respiratoria')),
                ('examen', models.TextField(blank=True, null=True, verbose_name='Examenes Realizados')),
                ('trata', models.TextField(blank=True, null=True, verbose_name='Tratamientos Aplicados')),
                ('fechac', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fechaa', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regmedic.Mascota')),
            ],
            options={
                'verbose_name_plural': 'Consultas',
                'ordering': ['-fechac'],
            },
        ),
    ]
