# Generated by Django 3.0.7 on 2022-01-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regmedic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cont_dias',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='consulta',
            name='cont_dias',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='despa',
            name='cont_dias',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='mascota',
            name='cont_dias',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='cont_dias',
            field=models.IntegerField(default=3),
        ),
    ]
