# Generated by Django 3.0.7 on 2022-01-14 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regmedic', '0002_auto_20220114_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='prox_cita',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='prox_cita',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='despa',
            name='prox_cita',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='prox_cita',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='prox_cita',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
