# Generated by Django 3.0.7 on 2022-01-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regmedic', '0003_auto_20220114_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cont_dias',
            field=models.IntegerField(default=3, verbose_name='Proxima Cita'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='cont_dias',
            field=models.IntegerField(default=3, verbose_name='Proxima Cita'),
        ),
        migrations.AlterField(
            model_name='despa',
            name='cont_dias',
            field=models.IntegerField(default=3, verbose_name='Proxima Cita'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='cont_dias',
            field=models.IntegerField(default=3, verbose_name='Proxima Cita'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='cont_dias',
            field=models.IntegerField(default=3, verbose_name='Proxima Cita'),
        ),
    ]
