# Generated by Django 3.0.7 on 2022-01-14 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regmedic', '0004_auto_20220114_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cont_dias',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='prox_cita',
            field=models.DateField(default=datetime.date.today, verbose_name='Proxima Cita'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='cont_dias',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='prox_cita',
            field=models.DateField(default=datetime.date.today, verbose_name='Proxima Cita'),
        ),
        migrations.AlterField(
            model_name='despa',
            name='cont_dias',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='despa',
            name='prox_cita',
            field=models.DateField(default=datetime.date.today, verbose_name='Proxima Cita'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='cont_dias',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='prox_cita',
            field=models.DateField(default=datetime.date.today, verbose_name='Proxima Cita'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='cont_dias',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='prox_cita',
            field=models.DateField(default=datetime.date.today, verbose_name='Proxima Cita'),
        ),
    ]
